# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\" \n\x08Operands\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x05\x32\x80\x01\n\nCalculator\x12\x1b\n\x03\x41\x64\x64\x12\t.Operands\x1a\x07.Result\"\x00\x12\x1b\n\x03Sub\x12\t.Operands\x1a\x07.Result\"\x00\x12\x1b\n\x03Mul\x12\t.Operands\x1a\x07.Result\"\x00\x12\x1b\n\x03\x44iv\x12\t.Operands\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERANDS']._serialized_start=18
  _globals['_OPERANDS']._serialized_end=50
  _globals['_RESULT']._serialized_start=52
  _globals['_RESULT']._serialized_end=75
  _globals['_CALCULATOR']._serialized_start=78
  _globals['_CALCULATOR']._serialized_end=206
# @@protoc_insertion_point(module_scope)
