# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import miner_pb2 as miner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in miner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MinerStub(object):
    """Definição do serviço Miner
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTransactionID = channel.unary_unary(
                '/Miner/GetTransactionID',
                request_serializer=miner__pb2.Empty.SerializeToString,
                response_deserializer=miner__pb2.TransactionIDResponse.FromString,
                _registered_method=True)
        self.GetChallenge = channel.unary_unary(
                '/Miner/GetChallenge',
                request_serializer=miner__pb2.TransactionRequest.SerializeToString,
                response_deserializer=miner__pb2.ChallengeResponse.FromString,
                _registered_method=True)
        self.GetTransactionStatus = channel.unary_unary(
                '/Miner/GetTransactionStatus',
                request_serializer=miner__pb2.TransactionRequest.SerializeToString,
                response_deserializer=miner__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SubmitChallenge = channel.unary_unary(
                '/Miner/SubmitChallenge',
                request_serializer=miner__pb2.SubmitRequest.SerializeToString,
                response_deserializer=miner__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.GetWinner = channel.unary_unary(
                '/Miner/GetWinner',
                request_serializer=miner__pb2.TransactionRequest.SerializeToString,
                response_deserializer=miner__pb2.WinnerResponse.FromString,
                _registered_method=True)
        self.GetSolution = channel.unary_unary(
                '/Miner/GetSolution',
                request_serializer=miner__pb2.TransactionRequest.SerializeToString,
                response_deserializer=miner__pb2.SolutionResponse.FromString,
                _registered_method=True)


class MinerServicer(object):
    """Definição do serviço Miner
    """

    def GetTransactionID(self, request, context):
        """Nome: getTransactionID()
        Retorna o valor atual <int> da transação com desafio pendente.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChallenge(self, request, context):
        """Nome: getChallenge()
        Retorna o valor do desafio. Retorne -1 se o transactionID for inválido.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionStatus(self, request, context):
        """Nome: getTransactionStatus()
        Retorna 0 (resolvido), 1 (pendente), -1 (inválido).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitChallenge(self, request, context):
        """Nome: submitChallenge()
        Retorna 1 (válida), 0 (inválida), 2 (já solucionado), -1 (inválido).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWinner(self, request, context):
        """Nome: getWinner()
        Retorna clientID, 0 (sem vencedor), -1 (inválido).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSolution(self, request, context):
        """Nome: getSolution()
        Retorna (status, solução, desafio).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTransactionID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionID,
                    request_deserializer=miner__pb2.Empty.FromString,
                    response_serializer=miner__pb2.TransactionIDResponse.SerializeToString,
            ),
            'GetChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChallenge,
                    request_deserializer=miner__pb2.TransactionRequest.FromString,
                    response_serializer=miner__pb2.ChallengeResponse.SerializeToString,
            ),
            'GetTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionStatus,
                    request_deserializer=miner__pb2.TransactionRequest.FromString,
                    response_serializer=miner__pb2.StatusResponse.SerializeToString,
            ),
            'SubmitChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitChallenge,
                    request_deserializer=miner__pb2.SubmitRequest.FromString,
                    response_serializer=miner__pb2.SubmitResponse.SerializeToString,
            ),
            'GetWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWinner,
                    request_deserializer=miner__pb2.TransactionRequest.FromString,
                    response_serializer=miner__pb2.WinnerResponse.SerializeToString,
            ),
            'GetSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSolution,
                    request_deserializer=miner__pb2.TransactionRequest.FromString,
                    response_serializer=miner__pb2.SolutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Miner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Miner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Miner(object):
    """Definição do serviço Miner
    """

    @staticmethod
    def GetTransactionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/GetTransactionID',
            miner__pb2.Empty.SerializeToString,
            miner__pb2.TransactionIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/GetChallenge',
            miner__pb2.TransactionRequest.SerializeToString,
            miner__pb2.ChallengeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/GetTransactionStatus',
            miner__pb2.TransactionRequest.SerializeToString,
            miner__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/SubmitChallenge',
            miner__pb2.SubmitRequest.SerializeToString,
            miner__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/GetWinner',
            miner__pb2.TransactionRequest.SerializeToString,
            miner__pb2.WinnerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Miner/GetSolution',
            miner__pb2.TransactionRequest.SerializeToString,
            miner__pb2.SolutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
